### ISSUE TITLE
docker-compose-develop linux support

### ISSUE THREAD

**Issue by edwardpmorris** [Skydipper/control-tower#41]
Would it be possible to add the line, so as to enable running local version in Ubuntu 18.04?
```
...
volumes:
#      - ./app:/opt/control-tower/app
      - /var/run/docker.sock:/var/run/docker.sock
extra_hosts:
      - "mymachine:$MYMACHINE"
```

**Comment by tiagojsag** [comment]
That line was there actually because of MacOS, and is not needed on Linux. You probably are not using the correct env vars, please refer to the README for instruction on running this, specifically about the `dev.env` file. 

Closing
